### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by bhajneet** [shabados/viewer#20]
Proposed set up:

Enter - activate selection
Tab - advance selection
Shift-Tab - back one selection
Down Arrow - Scroll page down
Up Arrow - Scroll page up
Right Arrow - change page forward one (if no pages left, notify user)
Left Arrow - change page backward one (if no pages left, notify user)
Ctrl {Left,Right} Arrow - change bar for page while ctrl is held down, once ctrl is let go activate page, if esc is hit or mouse is clicked during ctrl down, cancel.

**Comment by bhajneet** [comment]
Is the following possible for up/down arrow?

* User selects line
* User hits down arrow
* Program takes highlighted line, finds it's mid-point horizontally, then checks for a line below that mid-point and (if exists) highlights it

**Comment by bhajneet** [comment]
Page up and Page down should either be moving multiple lines up and down or actually changing 'pages', not acting as home/end keys

**Comment by bhajneet** [comment]
>Ctrl {Left,Right} Arrow - change bar for page while ctrl is held down, once ctrl is let go activate page, if esc is hit or mouse is clicked during ctrl down, cancel.

This wasn't implemented according to spec. It should be showing the trackbar move with an indication of which page. User should be allowed to hold right and left arrows to move trackbar quickly to a rough area and then fine tune with individual taps of right and left arrow. User should be able to cancel changing a page by hitting Esc/clicking-mouse-somewhere while holding ctrl down.

It's current implementation is good enough (though breaks history / browser back/forward buttons). However, I would still at least insist on seeing the trackbar's position highlighted at the bottom instead of relying on user noting the address bar url when changing pages.

**Comment by Harjot1Singh** [comment]
Up and down has been implemented, but without using the midpoint, since that is non-trivial/undefined when the line spans more than 1 line

**Comment by saihaj** [comment]
Is there anything missing ?
