### ISSUE TITLE
GitHub Auth and stats

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/viewer#3]
Show name of user, open/closed issues, and other stats.

**Comment by saihaj** [comment]
Can you tell more ?

**Comment by AkalUstat** [comment]
is this basically: Login with Github in viewer => you can now see your name, and profile page with open issues/stats?

**Comment by Harjot1Singh** [comment]
Pretty much, but it may need some rescoping since the shift in direction of the viewer

**Comment by bhajneet** [comment]
I think this will tie more into the API later, where you will have personal notes/synced bookmarks etc.
