### ISSUE TITLE
Rewrite using hooks, TS, & upgrade all depedencies

### ISSUE THREAD

**Issue by saihaj** [shabados/viewer#316]
**Is your feature request related to a problem? Please describe.**
Frontend for this project was written when react hooks weren't a thing. All the new components we write are functional components.  Issues I have with this:
1. Red browser console on dev bothers me a lot - incorrect prop types
2. I find it difficult to follow class based components (they are ancient)

**Describe the solution you'd like**
I would like to rewrite all the ancient class components and convert them to use hooks. In all this I would like to fix all the errors/warnings I get in browser consoles. I am even down to write this in Typescript. Work will be done in multiple PR's that will make it easier for maintainers to review the code and this should be started after  #309 is merged and so we have some sort of CI pipeline which should also help in PR review.

**Describe alternatives you've considered**
I made an attempt to rewrite using hooks https://github.com/shabados/viewer/pull/298. I mentioned this in the PR before [closing it](https://github.com/shabados/viewer/pull/298#issuecomment-674469619)
> * There are other ancient class based components.
> * There is some additional work that needs to be done here so it is actually better to refactor then

**Random Ideas (Something I would like to do in future)**
Write this using NextJS and have serverless backend that is a graphql endpoint. I made an attempt but the issues backend gets gets too big maybe because of DB package and it exceeds the size limit for the function to run. At least size was the issue with [azure function](https://github.com/saihaj/graphql-gurbani-azure-func) that I worked on. I think this is something we can do the DB package so that it makes it easier for developers to make serversless backends and host on azure functions, CloudFlare workers, AWS lambda and etc. 

**Additional context**
I have constantly bugged @Harjot1Singh for this : )

**Comment by Harjot1Singh** [comment]
This is done!
