### ISSUE TITLE
Allow user to change branches

### ISSUE THREAD

**Issue by bhajneet** [shabados/viewer#32]
In the future once these changes are being pushed to the masses, it might help to have a separate branch for the first pass-through that we can re-check for errors before pushing to the master branch.

In that case users on the db-viewer need to be able to select that branch

**Comment by Harjot1Singh** [comment]
Might rewrite it to not have a backend, and exclusively use the GitHub repo as the backend, that way, you could easily auto-generate pull requests since you’re working directly with the JSON, switch branches etc etc easily

**Comment by bhajneet** [comment]
Yes, that makes more sense. The other option to look into is locally
setting up a git repo for the user. Because we want them to eventually
publish their own PRs from the viewer.

**Comment by Harjot1Singh** [comment]
https://api.github.com/repos/ShabadOS/database/branches
